services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: caveo_api_database
    environment:
      - POSTGRES_USER=${DB_USER:-caveo_api}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-caveo_api}
      - POSTGRES_DB=${DB_NAME:-caveo_api}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - .postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-caveo_api} -d ${DB_NAME:-caveo_api}",
        ]
      interval: 5s
      timeout: 2s
      retries: 1
